version: "3.9"

services:

  backend:
    build: ./backend
    depends_on:
      - db
    tty: true
    ports:
      - 8000:8000
      - "9229:9229"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    volumes:
      - ./backend:/usr/src/app:rw

  db:
    image: postgres:latest
    restart: always
    platform: linux/x86_64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
  
  playwright:
    image: mcr.microsoft.com/playwright:bionic
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000  # バックエンドのURLを環境変数として設定する
    volumes:
      - ./e2e-tests:/e2e-tests  # Playwrightのテストスクリプトをマウントする

volumes:
  pgdata:
